$('.ui.radio.checkbox')
  .checkbox()
;

$('#submit').click(function () {

    let output = `[olddivbox=white][center][lssdheader][/lssdheader]
[b][size=85]FIELD TRAINING OBSERVATION REPORT[/size][/b]
[size=85]LOS SANTOS COUNTY SHERIFF'S DEPARTMENT — FIELD TRAINING PROGRAM[/size][/center]
                [hr][/hr]
                [table=Arial]
                [tr]
                [td][size=75][b]REPORT DATE[/b][/size][/td]
                [td][size=75][b]REPORT TIME[/b][/size][/td]
                [td][size=75][b]PHASE #[/b][/size][/td][/tr]
                [tr]
                [td][size=75]${$('input[name="date"]').val()}[/size][/td]
                [td][size=75]${$('input[name="time"]').val()}[/size][/td]
                [td][size=75]${$('input[name="phase"]').val()}[/size][/td]
                [/tr]
                [/table][hr][/hr]
                [table=Arial]
                [tr]
                [td][size=75][b]TRAINEE NAME[/b][/size][/td]
                [td][size=75][b]EMPLOYEE NUMBER[/b][/size][/td]
                [td][size=75][b]FTO NAME[/b][/size][/td]
                [td][size=75][b]EMPLOYEE NUMBER[/b][/size][/td][/tr]
                [tr]
                [td][size=75]${$('input[name="trainee_first"]').val()} ${$('input[name="trainee_last"]').val()}[/size][/TD]
                [td][size=75]${$('input[name="trainee_serial"]').val()}[/size][/TD]
                [td][size=75]${$('input[name="fto_first"]').val()} ${$('input[name="fto_last"]').val()}[/size][/TD]
                [td][size=75]${$('input[name="fto_serial"]').val()}[/size][/TD][/tr][/table][hr][/hr][table=Arial][tr]
[td][size=85][b][center]CATEGORICAL EVALUATION[/center][/b][/size][/td][/tr][/table][hr][/hr]
[table=Arial]
[tr]
[td][size=75][justify][b]INSTRUCTIONS:[/b]
[indent=25]C — A rating of C (Competent) is the minimum required to be considered at standard for a solo patrol deputy.
S — A rating of S (Superior) denotes outstanding performance and shall only be attributed if the trainee exceeds expectations.
N/I — A rating of N/I (Needs Improvement) shall be ticked to denote needing further training focus on a specific task.
N/O — A rating of N/O (Not Observed) shall be ticked for all situations which were not encountered in the patrol.
NRT — A rating of NRT (Not Responding to Training) shall be given if trainee has no reaction to training.[/indent][/justify][/size][/td][/tr][/table][hr][/hr]
[table=Arial][tr]
[td][size=85][b]ATTITUDE[color=transparent]-------------------------------------------------------------[/color][/b][/size][/td]
[td][size=85][b][center][center]RATING[/center][/center][/b][/size][/td]
[tr]
[td][size=85]Acceptance of Feedback/Criticism[/size][/td]
[td][size=85][center][center]${$('input[name="field1"]:checked').val()}[/center][/center][/td]
[tr]
[td][size=85]Attitude toward Police Work[/size][/td]
[td][size=85][center]${$('input[name="field2"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Integrity/Ethics[/size][/td]
[td][size=85][center]${$('input[name="field3"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Leadership[/size][/td]
[td][size=85][center]${$('input[name="field4"]:checked').val()}[/center][/td]
[/table]
[hr][/hr]
[table=Arial][tr]
[td][size=85][b]APPEARANCE[color=transparent]-------------------------------------------------------[/color][/b][/size][/td]
[td][size=85][b][center]RATING[/center][/b][/size][/td]
[tr]
[td][size=85]General Appearance[/size][/td]
[td][size=85][center]${$('input[name="field5"]:checked').val()}[/center][/td]
[/table]
[hr][/hr]
[table=Arial][tr]
[td][size=85][b]RELATIONSHIPS[color=transparent]---------------------------------------------------[/color][/b][/size][/td]
[td][size=85][b][center]RATING[/center][/b][/size][/td]
[tr]
[td][size=85]With Citizens/Community[/size][/td]
[td][size=85][center]${$('input[name="field6"]:checked').val()}[/center][/td]
[tr]
[td][size=85]With other Agencies' Members[/size][/td]
[td][size=85][center]${$('input[name="field7"]:checked').val()}[/center][/td]
[/table]
[hr][/hr]
[table=Arial][tr]
[td][size=85][b]PERFORMANCE[color=transparent]---------------------------------------------------[/color][/b][/size][/td]
[td][size=85][b][center]RATING[/center][/b][/size][/td]
[tr]
[td][size=85]Driving Skill: All Conditions[/size][/td]
[td][size=85][center]${$('input[name="field8"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Report Writing: Grammar/Spelling/Neatness[/size][/td]
[td][size=85][center]${$('input[name="field9"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Field Performance: Self-Initiated Field Activity[/size][/td]
[td][size=85][center]${$('input[name="field10"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Field Performance: General Conditions[/size][/td]
[td][size=85][center]${$('input[name="field11"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Officer Safety: General Conditions[/size][/td]
[td][size=85][center]${$('input[name="field12"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Control of Conflict: General Conditions[/size][/td]
[td][size=85][center]${$('input[name="field13"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Problem-solving Techniques/Decision-making[/size][/td]
[td][size=85][center]${$('input[name="field14"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Radio Communications[/size][/td]
[td][size=85][center]${$('input[name="field15"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Mobile Computer Terminal[/size][/td]
[td][size=85][center]${$('input[name="field16"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Use of Map Book/GPS: Orientation/Response Time[/size][/td]
[td][size=85][center]${$('input[name="field17"]:checked').val()}[/center][/td]
[/table]
[hr][/hr]
[table=Arial][tr]
[td][size=85][b]KNOWLEDGE[color=transparent]-------------------------------------------------------[/color][/b][/size][/td]
[td][size=85][b][center]RATING[/center][/b][/size][/td]
[tr]
[td][size=85]Department Policies and Procedures[/size][/td]
[td][size=85][center]${$('input[name="field18"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Criminal Law[/size][/td]
[td][size=85][center]${$('input[name="field19"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Criminal Procedure[/size][/td]
[td][size=85][center]${$('input[name="field20"]:checked').val()}[/center][/td]
[/table]
[hr][/hr]
[table=Arial][tr]
[td][size=85][b](( ROLEPLAY ))[color=transparent]-----------------------------------------------------[/color][/b][/size][/td]
[td][size=85][b][center]RATING[/center][/b][/size][/td]
[tr]
[td][size=85]Roleplay Quality[/size][/td]
[td][size=85][center]${$('input[name="field21"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Character Depth/Portrayal[/size][/td]
[td][size=85][center]${$('input[name="field22"]:checked').val()}[/center][/td]
[tr]
[td][size=85]Out-of-Character Demeanor[/size][/td]
[td][size=85][center]${$('input[name="field23"]:checked').val()}[/center][/td]
[tr]
[/table]
[hr][/hr]
[table=Arial][tr]
                [td][size=75][b][center]NARRATIVE EVALUATION[/center][/b][/size][/td][/tr][/table][hr][/hr]
                [table=Arial]
                [tr]
                [td][size=75][justify][b]INSTRUCTIONS:[/b] Parts A & B — Based on the completed FTOR, determine the trainee’s MOST and LEAST satisfactory performance. Part C — Provide a narrative of each documented situation that you and your trainee encountered during your Observation Patrol.[/justify][/size][/td][/tr][/table][hr][/hr]
                [table=Arial]
                [tr][td][size=75][b]PART A. MOST SATISFACTORY PERFORMANCE[/b][/size][/TD][/TR]
                [tr][td][size=75]${$('#positive').val()}[/size][/TD][/TR][/table][hr][/hr]
                [table=Arial]
                [tr][td][size=75][b]PART B. LEAST SATISFACTORY PERFORMANCE[/b][/size][/TD][/TR]
                [tr][td][size=75]${$('#negative').val()}
[/size][/TD][/TR][/table][hr][/hr]
                [table=Arial]
                [tr][td][size=75][b]PART C. DOCUMENTED SITUATIONS (DS)[/b][/size][/TD][/TR]
                [tr][td][size=75]${$('#documented').val()}[/size][/TD][/TR][/table][hr][/hr]
                [table=Arial]
                [tr]
                [td][size=75][b][center]SIGNATURES[/center][/b][/size][/td][/tr][/table][hr][/hr]
                [table=Arial]
                [tr]
                [td][size=75][b]TRAINEE SIGNATURE[/b][/size][/td]
                [td][size=75][b]DATE[/b][/size][/td][/tr]
                [tr]
                [td][size=75]${$('input[name="trainee_first"]').val()} ${$('input[name="trainee_last"]').val()}[/size][/TD]
                [td][size=75]${$('input[name="date"]').val()}[/size][/TD][/tr]
                [tr]
                [td][size=75][b]FTO SIGNATURE[/b][/size][/td]
                [td][size=75][b]DATE[/b][/size][/td][/tr]
                [tr]
                [td][size=75]${$('input[name="fto_first"]').val()} ${$('input[name="fto_last"]').val()}[/size][/TD]
                [td][size=75]${$('input[name="date"]').val()}[/size][/TD][/tr][/table]
                [hr][/hr]

   [table=Arial]
                [tr]
                [td][size=75][b][center]FEEDBACK FORM (TRAINEE USE ONLY)[/center][/b][/size][/td][/tr][/table][hr][/hr]
                [table=Arial]
                [tr]
                [td][size=75][justify][b]INSTRUCTIONS:[/b]
At the completion of the Field Training Patrol, the trainee should submit a confidential performance evaluation on their FTO.

The FTP Command will review each FTO Feedback that is completed by a  trainee. This will remain confidential information between FTP Command and the trainee. The information will be used to improve the overall performance of the FTO as a trainer and evaluator.

[b][url=https://docs.google.com/forms/d/e/1FAIpQLScx0885aRp4uJtaxZPbAC_qyHoN5LFQ40XyXEpwymcfN5ay8A/viewform]FTO Feedback Form[/url][/b][/justify][/size][/td][/tr][/table][hr][/hr]
      [/olddivbox]`

    $('#output').val(output);
});

$('#copy').click(function() {
    
  var copyText = document.getElementById('output');

  /* Select the text field */
  copyText.select();
  copyText.setSelectionRange(0, 99999); /* For mobile devices */

   /* Copy the text inside the text field */
  navigator.clipboard.writeText(copyText.value);

});